branch-defaults:
  deploy:
    environment: HuyProxy-env
environment-defaults:
  HuyProxy-env:
    branch: null
    repository: null
global:
  application_name: huy-proxy
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
